version: 2
jobs:
  build-deploy:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Build files
          command: npm run build
      - run:
          name: Deploy
          command: node scripts/deploy
#       - persist_to_workspace:
#           root: .
#           paths:
#             - build
#   deploy:
#     docker:
#       - image: circleci/python:3.6.1
#     environment:
#       AWS_DEFAULT_OUTPUT: json
#     steps:
#       - attach_workspace:
#           at: workspace
#       - run:
#           name: Install awscli
#           command: |
#             python3 -m venv venv
#             . venv/bin/activate
#             pip install awscli
#       - run:
#           name: Upload files
#           command: |
#             . venv/bin/activate
#             aws s3 sync workspace/build s3://$BUCKET_NAME --delete
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy
      # - deploy:
      #     requires:
      #       - build
      #     filters:
      #       branches:
      #         only: master