version: 2
jobs:
  build-deploy:
    docker:
      - image: circleci/node:10.13.0
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install packages
          command: npm install
      - run:
          name: Build files
          command: npm run build
      - run:
          name: Config git
          command: |
            git config --global user.email "michaeldong21@gmail.com" # TODO: Move to env variable
            git config --global user.name "Bot" # TODO: Move to env variable
      - run:
          name: Deploy
          command: node scripts/deploy
workflows:
  version: 2
  build-deploy:
    jobs:
      - build-deploy